### ISSUE TITLE
unexpected behaviour of choice_active() 

### ISSUE THREAD

**Issue by f3fora** [L3MON4D3/Dotfiles#1]
Sometimes it happen that `require('luasnip').choice_active()` returns `true` even if no snippet exists, for example after `LuaSnipUnlinkCurrent` execution or because `history = false`.

Moreover if no snippets exists, `LuaSnipUnlinkCurrent` raises an error: 'LuaSnip/lua/luasnip/init.lua:82: attempt to index a nil value'. I think having a `print('Hey! no more snippet here')` should be cooler.

**Comment by L3MON4D3** [comment]
Good points, would you mind opening this same issue in the Luasnip-repo? I'll give you a more detailed response on there :)

**Comment by f3fora** [comment]
you're right. Wrong project. 
Please change the link of snippet examples...

**Comment by L3MON4D3** [comment]
Do you mean the one in README? I have it in there to show some more examples which aren't covered in the 'official' ones. You've got a point though, a link to the official ones is missing, adding it should avoid confusion as well.
